config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'

  get 'reviews/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create, :show]


  resource :session, only: [:new, :create, :destroy]
  get 'logout', to: "sessions#destroy", as: :logout
  get 'login', to: "sessions#create", as: :login




  namespace :admin do
    resources :users 
  end    

  root to: 'movies#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  
  SEARCH_OPTIONS = {
    0 => 'Search all movies by runtime',
    1 => 'Less than 90 minutes',
    2 => 'Between 90 and 120 minutes',
    3 => 'Over 120 minutes'
  }

  scope :title_director_query, -> (search) {where("title LIKE ? OR director LIKE ?", "%#{search}%", "%#{search}%")}
  scope :runtime_query1, -> (runtime) {where("runtime_in_minutes < ?", 90)}
  #checks for runtimes between 90 and 120 minutes
  scope :runtime_query2, -> (runtime) {where("runtime_in_minutes > ? AND runtime_in_minutes < ?", 90, 120)}
  #checks for runtimes over 120 minutes
  scope :runtime_query3, -> (runtime) {where("runtime_in_minutes > ?", 120)}


  has_many :reviews, dependent: :destroy
  mount_uploader :image, ImageUploader


  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true, length:{maximum: 215}
  validates :release_date, presence: true

  validate :release_date_is_in_the_past

  def review_average
    reviews.sum(:rating_out_of_ten) / reviews.size unless reviews.empty?
  end 


  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :user, presence: true
  validates :text, presence: true

  validates :rating_out_of_ten, numericality: {only_integer: true}
  validates :rating_out_of_ten, numericality: {greater_than_or_equal_to: 1}
  validates :rating_out_of_ten, numericality: {less_than_or_equal_to: 10}
end

app/models/user.rb
class User < ApplicationRecord

  #adds a 'virtual' attribute to the model, that does not get saved in the DB. We don't want to store the user's plaintext password in our DB, just the digested version.
  has_secure_password
  paginates_per 10
  
  has_many :reviews, dependent: :destroy

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20}, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action do
    unless current_user.admin?
      flash[:notice] = "Access denied - only admins allowed!"
      redirect_to '/'
    end
  end

  def index
    @users = User.order("id").page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = (0..8).map {(65 + rand(26)).chr}.join #generates password for user
    if @user.save
      UserMailer.admin_welcome_email(@user).deliver_now
      redirect_to admin_users_path, notice: "New user created with username #{@user.email}."
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_email(@user).deliver_now
    @user.destroy
    redirect_to admin_users_path, notice: "User deleted"
  end

  protected
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin)
  end

end

#admins should never know users passwords - should not require it in the strong params! Need separate create field here! Create random pw which is sent to user - they log in and immediately change pw. 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
    @movies = @movies.title_director_query(params[:search]) if params[:search].present?
    @movies = @movies.runtime_query1(params[:runtime_in_minutes]) if params[:runtime_in_minutes] == "1"
    @movies = @movies.runtime_query2(params[:runtime_in_minutes]) if params[:runtime_in_minutes] == "2"
    @movies = @movies.runtime_query3(params[:runtime_in_minutes]) if params[:runtime_in_minutes] == "3"
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted succesfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie), notice: "#{@movie.title} updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end
  

  protected
  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :description, :image, :remove_image, :remote_image_url
      )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      # if user.admin
      #   session[:admin_id] = user.id
      # end
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}"
    else
      # binding.pry
      flash.now[:alert] = "Log in failed."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Logged out successfully!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id #auto log in here
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
     

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h2>Users</h2>

<%= link_to "Create a new user", new_admin_user_path %><br>

<%= paginate @users %>
<div class="container">
  <table class="responsive-table bordered highlight">
    <thead>
      <tr>
        <th data-field="id">User ID</th>
        <th data-field="email">Email</th>
        <th data-field="first">First</th>
        <th data-field="last">Last</th>
    </thead>
    <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= link_to user.id, admin_user_path(user)%></td>
          <td><%= user.email %></td>
          <td><%= user.firstname %></td>
          <td><%= user.lastname %></td>
          <td><% if user.admin %><strong>Admin</strong><% end %></td>
    <% end %>
    </tbody>
      </tr>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <%= form_for @user, url: admin_users_path(@user) do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created: 
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.check_box :admin, {}, "true", "false" %>
      <%= f.label :admin %>
    </div> 
    <div><%= f.submit "Submit" %></div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<h1>User details</h1>

<%= link_to "Delete this user", admin_user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete this user? This cannot be undone"} %></h2>

<p>Full name: <%= @user.full_name %></p>
<p>ID: <%= @user.id %></p>
<p>Email: <%= @user.email %></p>
<p>Profile creation date: <%= @user.created_at %></p>
<p>Profile last updated: <%= @user.updated_at %></p>
<% if @user.admin %></p>
  <p><strong>Admin</strong></p>
<% end %>

<%= link_to "Back to all users", admin_users_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer #ffa726 orange lighten-1">
  
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Rotten Mangoes</h5>
        <p class="grey-text text-lighten-4">The best place for reviews</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <% if current_user %>
        <ul>
          <li class="grey-text text-lighten-4">Signed in as <%= current_user.full_name %>(<%= link_to "Log out", logout_path, {class: "blue-text text-darken-2"} %>)</li>
          <% if current_user.admin %>
            <li class="grey-text text-lighten-4">Signed in as admin.</li>
            <li class="grey-text text-lighten-4">(<%= link_to "View all users", admin_users_path, {class:"blue-text text-darken-2"} %> or <%= link_to "create new user", new_admin_user_path, {class:"blue-text text-darken-2"} %>)</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
    <% else %>
      <ul>
        <li><%= link_to "Log in", login_path, {class:"blue-text text-darken-2"} %></li>
        <li><%= link_to "Sign up", new_user_path, {class:"blue-text text-darken-2"} %></li>
      </ul>
    <% end %>  
    </div>
</div>
</div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Chris V
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangoes</title>
    <%= csrf_meta_tags %>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body class="#fffde7 yellow lighten-5">
    <nav>
    <div class="nav-wrapper #ffa726 orange lighten-1">
      <a href="/" class="brand-logo">Rotten Mangoes</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">User profile</a></li>
      </ul>
    </div>
  </nav>
        
  <script type="text/javascript" src="js/materialize.min.js"></script>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
        <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %>
          <% end %>
        </ul>
      </div>
  <% end %>
  <div class="form-field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="form-field">
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div class="form-field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-field">
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :remote_image_url %><br>
    <%= f.text_field :remote_image_url %>
  </div>
  <div>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>
  <div class="form-field">
  <%= f.submit "Save" %>
  </div>
<% end %>  

app/views/movies/_movie.html.erb
<div class="col m6">
  <div class="card horizontal hoverable small">
    <div class="card-image">
      <%= link_to image_tag(movie.image.thumb.url.to_s), movie_path(movie) %>
    </div>
    <div class="card-stacked">
      <div class="card-content"> 
        <h5 class="header"><%= movie.title %></h5>     
        <blockquote>
          <p><%= movie.description %></p>
        </blockquote>
        <p>Release date: <%= formatted_date(movie.release_date) %></p>
        <p>Director: <%= movie.director %></p>
        <p>Runtime: <%= movie.runtime_in_minutes %> minutes</p>
        <% if movie.review_average.nil? %>
          <p>Not enough reviews for average</p>
        <% else %>
          <p>Review average: <%= movie.review_average %>/10</p>
        <% end %>
        <%= link_to movie_path(movie) do %>
          <p>Click for more</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/_summary.html.erb
<div class="col m12">
  <div class="card horizontal hoverable large">
    <div class="card-image">
      <%= image_tag(movie.image.url.to_s) %>
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <h5 class="header"><%=movie.title %></h5>
          (<%= link_to "edit", edit_movie_path(movie) %>, <%= link_to "delete", movie_path(movie), method: :delete, data: {confirm: "Are you sure? This cannot be undone."} %>)
        <p>Directed by: <%= movie.director %></p>
        <p>Runtime: <%= movie.runtime_in_minutes %> minutes</p>
        <% wiki = Wikipedia.find(@movie.title) %>        
        <% unless wiki.summary.nil? %>
          <flowtext>
            <p><%= wiki.summary %><br>
          </flowtext>
          <small>Source: <a href="<%= wiki.fullurl %>">Wikipedia</a></small></p>
        <% else %>
          <flowtext>
            <p><%= movie.description %></p>
          </flowtext>
        <% end %>
      <% unless movie.review_average.nil? %>
        <h4>Average user rating: <%= movie.review_average %>/10</h4>
      <% else %>
      <h4>Not enough reviews for an average. <%= link_to "Add one?", new_movie_review_path(movie) %></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
  <div class="center">
   <img src="/images/film_camera1.png"> 
  </div>

<div class="container center">
  <div class="row">
    <div class="col s4 left">
      <%= form_tag(nil, method: "get", id: "search-form", role: 'search') do %>
        <%= search_field_tag :search, nil, placeholder: "Search by title or director" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
    <div class="col s4 center">
      <h4 class="grey-text">OR</h4>
    </div>
    <div class="col s4 right">
      <%= form_tag(nil, method: "get", id: "search-form") do %>
        <%= select_tag :runtime_in_minutes, options_for_select(Movie::SEARCH_OPTIONS.invert) %> 
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>
</div>

<div class="col s6 center">
  <%= link_to "Submit a new movie", new_movie_path %>
</div>



<div class="row">
  <%= render @movies %>

</div>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Add new movie</h2>

<div class="container">
  <%= render 'form' %>
</div>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %>



<div class="row">
<%= render 'summary', movie: @movie %>
</div>

<div class="container center">
  <% unless @movie.review_average.nil? %>
    <h3><em>Reviews of <%= @movie.title %></em></h3>
  <% end %>
</div>

<% if current_user %>
  <div class="row">
    <%= render @movie.reviews %>
  </div>
  <p><%= link_to "Write a review", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", login_path %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/_review.html.erb
<% unless review.movie.nil? %>
  <div class="col m4 small"> 
    <div class="card hoverable" id="movie-page-review">
      <div class="card-stacked">
        <div class="card-content">
          <p><%= review.text %></p>
          <p><%= review.rating_out_of_ten %>/10</p>
          <small>Posted by: </small>
            <%= link_to user_path(review.user) do %> 
            <small><%= review.user.full_name %></small>
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  </div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie!", movie_path(@movie) %><br>
<h2>Write a review of <em><%= @movie.title %></em></h2>

<%= form_for ([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul> 
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_new_user.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created: 
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
  <%= f.label :password %><br>
  <%= f.password_field :password %>
  </div>
  <div>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
  </div>
  <% unless current_user.nil? || current_user.admin == false %>
    <div>
      <%= f.label :admin %>
      <%= f.check_box :admin, {}, "true", "false" %>
    </div>
  <% end %>  
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_user.html.erb
<h2>User Details</h2>
<p>Name: <%= user.full_name %></p>
<p>Email: <%= user.email %></p>
<h2>User Reviews:</h2>

app/views/users/_user_reviews.html.erb
<% @user.reviews.each do |review| %>
  <% unless review.movie_id.nil? %>
   <div class="col m2 small"> 
    <div class="card hoverable">
      <div class="card-stacked">
        <div class="card-content">
          <p><%= review.text %></p>
          <p><%= review.rating_out_of_ten %>/10</p>
            <%= link_to movie_path(review.movie_id) do %> 
            <small><%= (Movie.find(review.movie_id)).title %></small>
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <%= link_to "Back to all movies", movies_path %>
  <h1>Sign up!</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created: 
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
    </div>
    <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
    </div>
    <div><%= f.submit "Submit" %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to "Back to main page", movies_path %>

<%= render @user %>

<div class="row">
<%= render 'user_reviews', user: @user %>
</div>